/* eslint-disable @typescript-eslint/no-explicit-any */
declare module '@jiaminghi/data-view' {
    export const fullScreenContainer: any
    export const borderBox1: any
    export const borderBox4: any
    export const borderBox11: any
    export const borderBox9: any
    export const borderBox8: any
    export const borderBox10: any
    export const borderBox3: any
    export const borderBox5: any
    export const borderBox2: any
    export const decoration5: any
    export const decoration9: any
    export const decoration8: any
    export const decoration10: any
    export const decoration4: any
    export const capsuleChart: any
    export const scrollBoard: any
    export const Loading: any
    export const activeRingChart: any
}
